#docker-compose.server.yml

services:
  leader-server-app:
    build: .
    image: leader-server:1.0
    container_name: leader-server
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
    ports:
      - "8012:5000"
    env_file:
      - .env
    networks:
      - leader-net
    volumes:
      - /srv/docker/leader/uploads/constituency_images:/app/uploads/constituency_images
      - /srv/docker/leader/uploads/leader_documents:/app/uploads/leader_documents
      - /srv/docker/leader/uploads/leader_images:/app/uploads/leader_images
      - /srv/docker/leader/uploads/media_corner:/app/uploads/media_corner
      - /srv/docker/leader/uploads/profile_images:/app/uploads/profile_images
      - /srv/docker/leader/uploads/user_feedbacks:/app/uploads/user_feedbacks

networks:
  leader-net:
    external: true
