// routes/leaderTimelineRoutes.js
const express = require('express');
const router = express.Router();
const {
  addTimelineEntries,
  getTimeline,
  updateTimelineEntries,
  deleteTimelineEntries,
  deleteTimelineById,
  createTimelineEntry
} = require('../controllers/leaderTimelineController');

const validateAppKey = require('../middleware/validateAppKey');
const authenticate = require('../middleware/authenticate');

// Get full or filtered timeline (sorted by date desc)
router.get('/', validateAppKey, getTimeline);

// Add one or more timeline entries
//router.post('/:regd_mobile_no', createTimelineEntry);
router.post('/', validateAppKey, authenticate, createTimelineEntry);

// Update one or more timeline entries
router.put('/', validateAppKey, authenticate, updateTimelineEntries);

// Delete one or more timeline entries
router.delete('/', validateAppKey, authenticate, deleteTimelineEntries); 

// Delete Timeline entry by _id
router.delete('/entry', validateAppKey, authenticate, deleteTimelineById); // _id-based which is generated by MongoDB during doc creation


module.exports = router;

