const express = require('express');
const router = express.Router();
const {
  fetchEducation,
  createEducation,
  addEducationEntry,
  updateEducation,
  deleteEducation,
  updateEducationById,
  deleteEducationById
} = require('../controllers/leaderEducationController');

const validateAppKey = require('../middleware/validateAppKey');
const authenticate = require('../middleware/authenticate');

// Optional: Debugging export keys
// console.log("leaderEducationController keys:", Object.keys(require('../controllers/leaderEducationController')));


router.get('/', validateAppKey, fetchEducation);
router.post('/', validateAppKey, authenticate, createEducation);
//router.get('/:mobile', validateAppKey, fetchEducation);

// 17/09/2025
// Add new education entry using query params
router.post('/entry', validateAppKey, authenticate, addEducationEntry);

// Update education entry using query params
router.put('/entry', validateAppKey, authenticate, updateEducationById);

// Delete education entry using Query params
router.delete('/entry', validateAppKey, authenticate, deleteEducationById); // _id-based which is generated by MongoDB during doc creation
router.delete('/', validateAppKey, authenticate, deleteEducation);

module.exports = router;
